//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filament
    {
        public int Id { get; set; }
        public string RectangleCollor { get; set; }
        public string BtnString1 { get; set; }
        public string BtnBackColor1 { get; set; }
        public string BtnStringColor1 { get; set; }
        public string BtnString2 { get; set; }
        public string BtnBackColor2 { get; set; }
        public string BtnStringColor2 { get; set; }
        public string BtnString3 { get; set; }
        public string BtnBackColor3 { get; set; }
        public string BtnStringColor3 { get; set; }
        public string BtnString4 { get; set; }
        public string BtnBackColor4 { get; set; }
        public string BtnStringColor4 { get; set; }
        public int Answer { get; set; }
    }
}
